config/routes.rb
Rails.application.routes.draw do
  get 'parser/index'
  # resources :parsers
  post 'parser/init', controller: 'ParserController#init'
  get 'parser/init', to: redirect('parser/index')

  root 'parser#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/android_device.rb
class AndroidDevice < ApplicationRecord
end

app/models/android_version.rb
class AndroidVersion < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/general_share.rb
class GeneralShare < ApplicationRecord
end

app/models/ios_device.rb
class IosDevice < ApplicationRecord
end

app/models/ios_version.rb
class IosVersion < ApplicationRecord
end

app/models/screen_resolution.rb
class ScreenResolution < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/parser_controller.rb
require 'csv'
# Main
class ParserController < ApplicationController
  include Parsers
  include Jsons
  include Utils

  def init
    GeneralShare.delete_all
    parser_csv(GeneralShare, "#{Rails.root}/files/general_share.csv")
    netmarketshare_parser_general_share
    statcounter_parser_general_share
    unity3d_parser_general_share
    w3schools_parser_general_share

    IosVersion.delete_all
    parser_csv(IosVersion, "#{Rails.root}/files/ios_version.csv")
    unity3d_parser_ios
    david_smith_parser_ios
    apple_parser_ios
    apteligent_parser_ios
    bugfender_parser_ios

    AndroidVersion.delete_all
    parser_csv(AndroidVersion, "#{Rails.root}/files/android_versions.csv")
    bugfender_parser_android_version
    android_parser_android_version
    appbrain_parser_android_version
    apteligent_parser_android_version
    unity3d_parser_android_version

    IosDevice.delete_all
    parser_csv(IosDevice, "#{Rails.root}/files/ios_devices.csv")
    bugfender_parser_ios_devices
    david_smith_parser_ios_devices
    unity3d_parser_ios_devices

    ScreenResolution.delete_all
    parser_csv(ScreenResolution, "#{Rails.root}/files/screen_resolutions.csv")
    statcounter_parser_screen_resolution
    # unity3d_parser_screen_resolution # disabled because of strange statistics

    AndroidDevice.delete_all
    parser_csv(AndroidDevice, "#{Rails.root}/files/android_devices.csv")
    appbrain_parser_android_devices
    redirect_to :back
  end

  def index
    @general_shares_json = general_shares_json
    @major_ios_versions_json = major_ios_versions_average_json
    @android_versions_json = android_versions_json
    @ios_devices_json = ios_devices_json
    @screen_resolutions_json = screen_resolutions_json
    @android_devices_json = android_devices_json
    # byebug
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parser_helper.rb
module ParserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta charset="utf-8">
<html>
  <head>
    <title>MobileStatistics</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://d3js.org/d3.v4.min.js"></script>
  </head>

  <body>
    <%= Gon::Base.render_data(init: true) %>
    <%= yield %>
  </body>
</html>

app/views/parser/index.html.slim
h1
  | Mobile statistics
= link_to 'Init', parser_init_url, method: :post
h1
script var CSS_COLOR_NAMES = ["AliceBlue","AntiqueWhite","Aqua","Aquamarine","Azure","Beige","Bisque","Black","BlanchedAlmond","Blue","BlueViolet","Brown","BurlyWood","CadetBlue","Chartreuse","Chocolate","Coral","CornflowerBlue","Cornsilk","Crimson","Cyan","DarkBlue","DarkCyan","DarkGoldenRod","DarkGray","DarkGrey","DarkGreen","DarkKhaki","DarkMagenta","DarkOliveGreen","Darkorange","DarkOrchid","DarkRed","DarkSalmon","DarkSeaGreen","DarkSlateBlue","DarkSlateGray","DarkSlateGrey","DarkTurquoise","DarkViolet","DeepPink","DeepSkyBlue","DimGray","DimGrey","DodgerBlue","FireBrick","FloralWhite","ForestGreen","Fuchsia","Gainsboro","GhostWhite","Gold","GoldenRod","Gray","Grey","Green","GreenYellow","HoneyDew","HotPink","IndianRed","Indigo","Ivory","Khaki","Lavender","LavenderBlush","LawnGreen","LemonChiffon","LightBlue","LightCoral","LightCyan","LightGoldenRodYellow","LightGray","LightGrey","LightGreen","LightPink","LightSalmon","LightSeaGreen","LightSkyBlue","LightSlateGray","LightSlateGrey","LightSteelBlue","LightYellow","Lime","LimeGreen","Linen","Magenta","Maroon","MediumAquaMarine","MediumBlue","MediumOrchid","MediumPurple","MediumSeaGreen","MediumSlateBlue","MediumSpringGreen","MediumTurquoise","MediumVioletRed","MidnightBlue","MintCream","MistyRose","Moccasin","NavajoWhite","Navy","OldLace","Olive","OliveDrab","Orange","OrangeRed","Orchid","PaleGoldenRod","PaleGreen","PaleTurquoise","PaleVioletRed","PapayaWhip","PeachPuff","Peru","Pink","Plum","PowderBlue","Purple","Red","RosyBrown","RoyalBlue","SaddleBrown","Salmon","SandyBrown","SeaGreen","SeaShell","Sienna","Silver","SkyBlue","SlateBlue","SlateGray","SlateGrey","Snow","SpringGreen","SteelBlue","Tan","Teal","Thistle","Tomato","Turquoise","Violet","Wheat","White","WhiteSmoke","Yellow","YellowGreen"];
script var general_shares_json = #{{@general_shares_json}}
script var major_ios_versions_json = #{{@major_ios_versions_json}}
script var android_versions_json = #{{@android_versions_json}}
div id="pieChart"
script var input_json = general_shares_json
= javascript_include_tag "general_shares"
script var input_json = major_ios_versions_json
= javascript_include_tag "general_shares"
/ = javascript_include_tag "ios_major_versions"
= javascript_include_tag "android_versions"
=javascript_include_tag "singleBarChart"
svg id="chart"